schema_version = "1.0.0"
id = "schalotte_tools"
version = "1.6.1"
name = "Schalotte Tools"
tagline = "Blender tools for the Schalotte project"
maintainer = "Tristan Weis"
type = "add-on"
website = "https://github.com/Plyrolith/schalotte_tools"
tags = ["Pipeline"]
blender_version_min = "4.5.0"
license = ["SPDX:GPL-3.0-or-later"]
